config/routes.rb
Rails.application.routes.draw do

  root 'shelters#index'

  resources :shelters do
    resources :animals do
      get 'adopt' => "animals#adopt"
      put 'complete_adoption' => "animals#complete_adoption"
    end
    resources :clients do
      resources :animals
    end
  end
  resources :animals do
    get 'donate' => "animals#donate"
    put 'complete_donation' => "animals#complete_donation"
    resources :toys
  end

end

app/models/animal.rb
class Animal < ActiveRecord::Base
  belongs_to :shelter
  belongs_to :client

  def owner
    if self.client
      self.client.name
    elsif self.shelter
      self.shelter.name
    else
      "I'm orphaned!"
    end
  end

  def adopt(client)
    shelter = self.shelter 
    shelter.animals.delete(self)
    client.animals << self 
  end

  def donate(shelter)
    client = self.client
    client.animals.delete(self)
    shelter.animals << self
  end

end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :shelter
  has_many :animals
end

app/models/shelter.rb
class Shelter < ActiveRecord::Base
  has_many :animals
  has_many :clients

  validates_presence_of :name
 
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController

  def index
    # @animals = Animal.all

  end

  def show
    @animal = Animal.find(params[:id])
  end

  def new
    @shelter = Shelter.find(params[:shelter_id])
    @animal = Animal.new
  end

  def create
    @shelter = Shelter.find(params[:shelter_id])

    @animal = @shelter.animals.new(safe_animal_parameters)

    if @animal.save
      flash[:notice] = "Your Animal is created"

      redirect_to shelter_path(@shelter)
    else
      render :new
    end
  end

  def adopt_pets
    @shelter = Shelter.find(params[:shelter_id])
    @animal = Animal.find(params[:animal_id])

    if !@shelter.animals.include?(@animal)
      redirect_to shelter_path(@shelter)
      flash[:notice] = "#{ @animal.name } Sorry your animal is no longer available in #{ @shelter.name }"
    end

  end

  def complete_adoption
    @client = Client.find(params[:animal]['client'])
    @animal = Animal.find(params[:animal_id])
    @animal.adopt(@client)
    redirect_to shelter_clients_path(@client.shelter, @client)
    flash[:notice] = "#{ @client.name } has adopted #{ @animal.name }"
  end

  def donate_pets
    @animal = Animal.find(params[:animal_id])
    @client = @animal.client

    if !@client.animals.include?(@animal)
      redirect_to client_path(@client)
      flash[:notice] = "#{ @animal.name } is no longer kept by #{ @client.name }"
    end
  end

  def complete_donation
    @animal = Animal.find(params[:animal_id])
    @shelter = Shelter.find(params[:animal]['shelter'])
    @animal.donate(@shelter)
    redirect_to shelter_path(@shelter)
    flash[:notice] = "#{ @animal.name } has been given to  #{ @shelter.name }"
  end

  private

  def safe_animal_parameters
    params.require(:animal).permit(:name, :species, :photo)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  def index
    @shelter = Shelter.find(params[:shelter_id])
    @clients = @shelter.clients
  end

  def show
    @client = Client.find(params[:id])
    @animals = @client.animals
  end

  def new
    @shelter = Shelter.find(params[:shelter_id])
    @client = @shelter.clients.new
  end

  def create
    @shelter = Shelter.find(params[:shelter_id])
    @client = @shelter.clients.new(safe_client_parameters)

    if @client.save
      flash[:notice] = "Your client is created"
      redirect_to shelter_path(@shelter)
    else
      render :new
    end
  end

  private

  def safe_client_parameters
    params.require(:client).permit(:name, :age, :photo)
  end
end

app/controllers/shelters_controller.rb
class SheltersController < ApplicationController

  def index
    @shelters = Shelter.all
  end

  def show
    @shelter = Shelter.find(params[:id])
    @clients = @shelter.clients
    @animals = @shelter.animals
  end
  
  def new
    @shelter = Shelter.new
  end

  def create
    @shelter = Shelter.new(safe_shelter_params)
    if @shelter.save
      flash[:notice] = "Your selter is created!"
      redirect_to shelters_path
    else
      render :new
    end
  end

  private

  def safe_shelter_params
    params.require(:shelter).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/adopt.html.erb
<h2>Adopt <%= @animal.name %> </h2>

<%= form_for([@shelter, @animal], url: { action: 'complete_adoption' }, html: { method: 'put' }) do |f| %>

  <p>Client to adopt <%= @animal.name %>: <%= f.collection_select(:client, Client.where(:shelte @shelter), :id, :name)  %></p>
  <p><%= f.submit %></p>
<% end %>

app/views/animals/donate.html.erb
<h2>Adopt <%= @animal.name %> </h2>

<%= form_for([@shelter, @animal], url: { action: 'complete_donation' }, html: { method: 'put' }) do |f| %>
  <p>Shelter to accept <%= @animal.name %>: <%= f.collection_select(:shelter, Shelter.all, :id, :name)  %></p>
  <p><%= f.submit %></p>
<% end %>

app/views/animals/new.html.erb
<h2>Please Add a new animal to <%= @shelter.name %> </h2>

<%= form_for [@shelter, @animal] do |f| %>
  <p>Name: <%= f.text_field :name%></p>
  <p>Species: <%= f.text_field :species%></p>
  <p>Photo: <%= f.text_field :photo%></p>
  <p><%= f.submit %></p>
  
<% end %>

app/views/animals/show.html.erb
<h1>Please meet your animal <%= @animal.name %></h1>

<ul>
  <li>Species: <%= @animal.species %></li>
  <li>Owner: <%= @animal.owner %></li>
</ul>

<% if @animal.shelter %>
  <p><%= link_to "Adopt #{ @animal.name }", shelter_animal_adopt_path(@animal.shelter, @animal) %></p>
<% elsif @animal.client %>
  <p><%= link_to "Donate #{ @animal.name }", animal_donate_path(@animal) %></p>
<% end %>

<img src="<%= @animal.photo %>" height="380px">

<p><%= link_to "Give #{ @animal.name } a new toy", new_animal_toy_path(@animal) %></p>

app/views/clients/index.html.erb
<h1>Clients</h1>

<ul>

<% @clients.each do |client| %>
  <li><%= link_to client.name, shelter_client_path(@shelter, client) %></li>
<% end %>

</ul>

app/views/clients/new.html.erb
<h2>Add a new client to <%= @shelter.name %> </h2>

<%= form_for [@shelter, @client] do |f| %>
  <p>Name: <%= f.text_field :name%></p>
  <p>Age: <%= f.text_field :age%></p>
  <p>Photo: <%= f.text_field :photo%></p>
  <p><%= f.submit %></p>
<% end %>

app/views/clients/show.html.erb
<<h1><%= @client.name %></h1>
<img src="<%= @client.photo %>" height='400'>
<h2>Shelter: <%= link_to @client.shelter.name, shelter_path(@client.shelter) %></h2>
<h2><%= @client.name %>'s animals:</h2>
<ul>
  <% @client.animals.each do |animal| %>
    <li><%= link_to animal.name, animal_path(animal) %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <h1><titl>GreenhousePet</title></titl>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class='container'>
  <div>
    <%# if notice %>
  <p class="alert alert-success"><%= notice %></p>
<%# end %>
<%# if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<%# end %>
  </div>
  <nav>
    <span><%= link_to "All Shelters", shelters_path %></span>
  </nav>

  <%= yield %>
  
</div><!-- /container  -->
</body>
</html>

app/views/shelters/_form.html.erb
<%= form_for @shelter.animal do |animal| %>

   <p>Animal Name: <%= shelter.text_field :name %></p>
   <p>Species: <%= shelter.text_field : %></p>
   <p> Photo: <%= shelter.text_field
   <p><%= photo.submit %></p>

<% end %

app/views/shelters/index.html.erb
<% @shelters.each do |k|  %>
  <p><%= link_to k.name, k %></p>
<% end %>
    

app/views/shelters/new.html.erb
<% if @shelter.errors.any? %>
  <div id="error_explanation">
    <p><%= pluralize(@shelter.errors.count, "error") %> prohibited this shelter from being saved:</p>
 
    <ul>
    <% @shelter.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= form_for @shelter do |f| %>
<p>Name: <%= f.text_field :name %></p>
<p><%= f.submit %></p>
<% end %>

app/views/shelters/show.html.erb
<h1><%= @shelter.name %></h1>

<p><%= link_to "Add an animal", new_shelter_animal_path(@shelter) %> | <%= link_to "Add a client", new_shelter_client_path(@shelter) %></p>

<h2>Our animals</h2>
<ul>
  <% @animals.each do |animal| %>
    <li><%= link_to animal.name, shelter_animal_path(@shelter, animal) %></li>
  <% end %>
</ul>

<p><%= link_to "New Client for #{@shelter.name }", new_shelter_client_path(@shelter) %></p>
<h2>Our clients</h2>
<ul>
  <% @clients.each do |client| %>
    <li><%= link_to client.name, shelter_client_path(@shelter, client) %></li>
  <% end %>
</ul>